feat(tsconfig): add support for ts 4.6 and ng14
NationalBankBelgium/code-style pull request #476
Opened 2024-02-06 14:47 UTC by mhenkens

## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x The commit message follows our guidelines: https://github.com/NationalBankBelgium/code-style/blob/master/CONTRIBUTING.md#-commit-message-guidelines
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Add support for TS 4.6 and angular 14

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

2024-02-07 10:48 UTC, SuperITMan requested changes
Some remarks. 

Could you the edit the tsconfig/README.md file in order to add the new versions and to adapt the latest version ?

2024-02-07 10:48 UTC, SuperITMan commented on lib/eslint/8.30.x/.eslintrc.json
Could you remove this file ?

2024-02-07 10:48 UTC, SuperITMan commented on lib/eslint/8.30.x/README.md
Could you remove this file ?

2024-02-07 10:48 UTC, SuperITMan commented on lib/eslint/8.30.x/package.json
Could you remove this file ?

2024-02-07 10:48 UTC, SuperITMan commented on lib/tsconfig/4.6.x/tsconfig.json
> +    "target": "es2020",
Could you add a comment about this change (previously it was es2015) in your commit message ?

Does the Angular recommends/forces to use the targert `es2020` ?

2024-02-09 08:44 UTC, ageorges-nbb approved these changes

2024-02-09 08:44 UTC, SuperITMan approved these changes

2024-02-09 08:44 UTC, merged